theme: jekyll-theme-cayman
title: Sanvi's Jekyll Page
description: Easy to access project updates!
email: sanvi11929@gmail.com
webserver: "sanvi1855544.github.io.com"
appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L
